name = "solid-playground"
type = "webpack"
account_id = ""
workers_dev = true
route = "playground.solidjs.com/*"
zone_id = ""
kv_namespaces = [ 
]

[site]
bucket = "./dist"
entry-point = "workers-site"
