type = "webpack"
account_id = ""
workers_dev = true
compatibility_date = "2021-10-23"
zone_id = ""

# wrangler publish --env=development
[env.development]
name = "solid-playground-dev"
route = "dev.playground.solidjs.com/*"
kv_namespaces = [ 
    { binding = "URLS", id = "", preview_id = "" }
]

# wrangler publish --env=production
[env.production]
name = "solid-playground"
route = "playground.solidjs.com/*"
kv_namespaces = [ 
    { binding = "URLS", id = "", preview_id = "" }
]

[site]
bucket = "./dist"
entry-point = "workers-site"
