type = "webpack"
account_id = ""
workers_dev = true
zone_id = ""
compatibility_date = "2021-10-23"
kv_namespaces = [ 
]

[env.development]
name = "solid-playground-dev"
route = "dev.playground.solidjs.com/*"

[env.production]
name = "solid-playground"
route = "playground.solidjs.com/*"

[site]
bucket = "./dist"
entry-point = "workers-site"